"""Module that implements 4 related duration-tracking concepts.

- TargetDuration:    how long an algorithm or part of an algorithm should run
- ProgressTracker:   generated by a TargetDuration when we ask to start tracking this duration
- Progress:          a snapshot of progress made so far, as reported by a ProgressTracker, which
can also be used to update a tqdm progress bar.
- Elapsed:           represents observed duration in terms of absolute time & iterations and can be
received from a ProgressTracker object.
"""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING

from max_div._core._utils import format_time_duration

if TYPE_CHECKING:
    from tqdm import tqdm


# =================================================================================================
#  TargetDuration
# =================================================================================================
class TargetDuration(ABC):
    """Base class specifying how long a solver step should run.

    Use the factory methods `seconds`, `minutes`, `hours` for wall-clock
    durations, or `iterations` for a fixed iteration count.  The `total_*`
    factories return a budget for the whole solve rather than for the step
    alone; see `TargetTotalTimeDuration`.
    """

    @abstractmethod
    def track(self) -> ProgressTracker:
        raise NotImplementedError

    @abstractmethod
    def value(self) -> float:
        """Numerical value (without unit) of the target duration."""
        raise NotImplementedError

    def started_now(self) -> TargetDuration:
        """Return the duration a solve starting now should run against.

        A duration measured from the start of the step that runs it returns itself;
        `TargetTotalTimeDuration` returns a copy anchored at this moment.  The copy is what keeps a
        budget reusable: a solver takes its own anchored duration rather than re-anchoring the one
        the caller passed in, which any other solver may still be holding.
        """
        return self

    def __repr__(self) -> str:
        return f"TargetDuration({self!s})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, TargetDuration) and (type(self) is type(other)) and (self.value() == other.value())

    def __hash__(self) -> int:
        return hash((type(self), self.value()))

    def __lt__(self, other: object) -> bool:
        if not isinstance(other, TargetDuration):
            return NotImplemented
        return self.value() < other.value()

    # -------------------------------------------------------------------------
    #  Factory methods
    # -------------------------------------------------------------------------
    @classmethod
    def seconds(cls, t_target_sec: float) -> TargetDuration:
        return TargetTimeDuration(t_target_sec)

    @classmethod
    def minutes(cls, t_target_min: float) -> TargetDuration:
        return TargetTimeDuration(t_target_min * 60.0)

    @classmethod
    def hours(cls, t_target_hours: float) -> TargetDuration:
        return TargetTimeDuration(t_target_hours * 3600.0)

    @classmethod
    def iterations(cls, n_iters: int) -> TargetDuration:
        return TargetIterationCount(n_iters)

    @classmethod
    def total_seconds(cls, t_total_sec: float) -> TargetDuration:
        return TargetTotalTimeDuration(t_total_sec)

    @classmethod
    def total_minutes(cls, t_total_min: float) -> TargetDuration:
        return TargetTotalTimeDuration(t_total_min * 60.0)

    @classmethod
    def total_hours(cls, t_total_hours: float) -> TargetDuration:
        return TargetTotalTimeDuration(t_total_hours * 3600.0)


class TargetTimeDuration(TargetDuration):
    """Wall-clock time duration target, created via `seconds`, `minutes`, or `hours`."""

    def __init__(self, t_target_sec: float) -> None:
        if t_target_sec <= 0:
            raise ValueError("t_target_sec must be > 0")
        self._t_target_sec = t_target_sec

    def value(self) -> float:
        return self._t_target_sec

    def __str__(self) -> str:
        return format_time_duration(self._t_target_sec, n_chars=8, pad=False)

    def track(self) -> ProgressTracker:
        return _TimeTracker(self._t_target_sec)

    def __mul__(self, other: float | int) -> TargetTimeDuration:
        if not isinstance(other, (float, int)):
            return NotImplemented
        return TargetTimeDuration(max(1e-9, self._t_target_sec * other))

    def __rmul__(self, other: float | int) -> TargetTimeDuration:
        return self.__mul__(other)


class TargetTotalTimeDuration(TargetTimeDuration):
    """Wall-clock budget for the whole solve, created via `total_seconds`, `total_minutes`, or `total_hours`.

    Where a `seconds` budget is spent by the optimization alone, this one also covers the distance
    store build and the initialization that precede it, and the optimization receives what those
    two leave.  The "How the Solver Works" page compares the budget kinds.

    The clock starts when the solver begins working: `build()` for a single solver, `solve()` for a
    portfolio, whose build only assembles configurations.  Each takes an anchored copy, so one
    budget object can configure any number of solvers; constructing this object also starts it,
    which is what a hand-assembled `MaxDivSolver` falls back on.

    **Build a single solver right before solving it.** Its deadline is fixed at `build()` -- that
    is what lets the budget cover the build -- so anything between the two comes out of the budget,
    including an earlier solve.  Build again to solve again.

    Neither the store build nor the initialization can be cut short, so a budget smaller than those
    two together is overshot, and the optimization is skipped rather than shortened.  A solve that
    reaches its optimization with nothing left says so through a `SolverBudgetWarning`.
    """

    def __init__(self, t_total_sec: float) -> None:
        super().__init__(t_total_sec)
        # monotonic() rather than perf_counter(): a portfolio's workers are separate processes, and
        # they read this deadline against their own clock.
        self._t_budget_start = time.monotonic()

    def started_now(self) -> TargetTotalTimeDuration:
        """Return a copy of this budget, anchored at this moment."""
        return TargetTotalTimeDuration(self._t_target_sec)

    def remaining_seconds(self) -> float:
        """Return how much of the budget is left, which is zero once it is spent."""
        return max(0.0, self._t_budget_start + self._t_target_sec - time.monotonic())

    def track(self) -> ProgressTracker:
        """Return a tracker over whatever is left of the budget, so a spent budget runs nothing."""
        return _TimeTracker(self.remaining_seconds())

    def __str__(self) -> str:
        return f"{super().__str__()} total"

    def __mul__(self, other: float | int) -> TargetTotalTimeDuration:
        if not isinstance(other, (float, int)):
            return NotImplemented
        scaled = TargetTotalTimeDuration(max(1e-9, self._t_target_sec * other))
        # keep the original's start, so scaling mid-solve does not hand back time already spent
        scaled._t_budget_start = self._t_budget_start
        return scaled


class TargetIterationCount(TargetDuration):
    """Fixed iteration count duration target, created via `iterations`."""

    def __init__(self, n_iters: int) -> None:
        if n_iters <= 0:
            raise ValueError("n_iters must be > 0")
        self._n_iters = n_iters

    def value(self) -> float:
        return float(self._n_iters)

    def __str__(self) -> str:
        return f"{self._n_iters:_} it."

    def track(self) -> ProgressTracker:
        return _IterationTracker(self._n_iters)

    def __mul__(self, other: float | int) -> TargetIterationCount:
        if not isinstance(other, (float, int)):
            return NotImplemented
        return TargetIterationCount(max(1, round(self._n_iters * other)))

    def __rmul__(self, other: float | int) -> TargetIterationCount:
        return self.__mul__(other)


# --- shorthand factory methods ---------------------------
iterations = TargetDuration.iterations
seconds = TargetDuration.seconds
minutes = TargetDuration.minutes
hours = TargetDuration.hours
total_seconds = TargetDuration.total_seconds
total_minutes = TargetDuration.total_minutes
total_hours = TargetDuration.total_hours


# =================================================================================================
#  ProgressTracker
# =================================================================================================
class ProgressTracker(ABC):
    """Class that tracks algorithm progress in iterations / time / ... and starts tracking upon construction."""

    def __init__(self) -> None:
        self._t_start = time.perf_counter()
        self._iter_count = 0

    def report_iterations_done(self, n: int) -> None:
        self._iter_count += n

    def iter_count(self) -> int:
        return self._iter_count

    def elapsed(self) -> Elapsed:
        return Elapsed(
            t_elapsed_sec=time.perf_counter() - self._t_start,
            n_iterations=self._iter_count,
        )

    def iters_per_second(self) -> float:
        t_elapsed = time.perf_counter() - self._t_start
        if (t_elapsed > 0.0) and (self._iter_count > 0):
            return self._iter_count / t_elapsed
        return 0.0

    @abstractmethod
    def get_progress(self) -> Progress:
        raise NotImplementedError


class _TimeTracker(ProgressTracker):
    def __init__(self, max_seconds: float) -> None:
        super().__init__()
        self._max_seconds = max_seconds
        self._n_total = max(1, int(max_seconds))

    def get_progress(self) -> Progress:
        est_iters_per_second = self.iters_per_second()
        t_elapsed = time.perf_counter() - self._t_start
        if t_elapsed >= self._max_seconds:
            fraction = 1.0
            est_n_iters_remaining = 0
        else:
            fraction = t_elapsed / self._max_seconds
            est_n_iters_remaining = max(1, int((self._max_seconds - t_elapsed) * est_iters_per_second))

        return Progress(
            tqdm_n_total=self._n_total,
            fraction=fraction,
            iter_count=self._iter_count,
            est_n_iters_remaining=est_n_iters_remaining,
            est_iters_per_second=est_iters_per_second,
        )


class _IterationTracker(ProgressTracker):
    def __init__(self, max_iters: int) -> None:
        super().__init__()
        self._max_iters = max_iters

    def get_progress(self) -> Progress:
        fraction = 1.0 if self._iter_count >= self._max_iters else self._iter_count / self._max_iters

        return Progress(
            tqdm_n_total=self._max_iters,
            fraction=fraction,
            iter_count=self._iter_count,
            est_n_iters_remaining=max(0, self._max_iters - self._iter_count),
            est_iters_per_second=self.iters_per_second(),
        )


# =================================================================================================
#  Progress
# =================================================================================================
@dataclass(frozen=True, slots=True)
class Progress:
    """Representation of progress made so far towards a target duration, including various meta-data."""

    # --- tqdm -----------------------------------
    tqdm_n_total: int  # total number of steps for tqdm progress bar

    # --- other ----------------------------------
    fraction: float  # fractional progress in [0,1]
    iter_count: int  # total number of iterations reported done
    est_n_iters_remaining: int  # estimated number of iterations remaining
    est_iters_per_second: float  # estimated number of iterations executed so far per second

    @property
    def tqdm_n_current(self) -> int:
        if self.fraction >= 1.0:
            return self.tqdm_n_total
        # report fractional progress, but limited to tqdm_n_total-1 in case we're not finished yet.
        return max(0, min(self.tqdm_n_total - 1, round(self.fraction * self.tqdm_n_total)))

    @property
    def est_progress_fraction_per_iter(self) -> float:
        """Estimated progress fraction increase per executed iteration."""
        est_total_iters = self.iter_count + self.est_n_iters_remaining
        # normally either iter_count or est_n_iters_remaining is >=1; just to be sure, we take max(1, ...)
        return 1.0 / max(1, est_total_iters)

    @property
    def is_finished(self) -> bool:
        return self.fraction >= 1.0

    def update_tqdm(self, pbar: tqdm) -> None:
        """Updates a tqdm progress bar to reflect current progress."""
        pbar.n = self.tqdm_n_current
        pbar.total = self.tqdm_n_total
        pbar.refresh()


# =================================================================================================
#  Elapsed
# =================================================================================================
@dataclass(frozen=True, slots=True)
class Elapsed:  # noqa: PLW1641 — value-semantics-only hot-path object; deliberately unhashable
    # --- data fields ----------------------------
    t_elapsed_sec: float
    n_iterations: int

    # --- equal ----------------------------------
    def __eq__(self, other: object) -> bool:
        # equal if...
        #   n_iterations is exactly equal
        #   t_elapsed_sec is equal within 1e-10 sec, which is < 1 clock cycle on typical modern hardware
        return (
            isinstance(other, Elapsed)
            and (self.n_iterations == other.n_iterations)
            and abs(self.t_elapsed_sec - other.t_elapsed_sec) < 1e-10
        )

    # --- math -----------------------------------
    def __add__(self, other: Elapsed | int) -> Elapsed:
        if other == 0:
            return self  # helps ensure sum() works correctly
        if not isinstance(other, Elapsed):
            return NotImplemented
        return Elapsed(
            t_elapsed_sec=self.t_elapsed_sec + other.t_elapsed_sec,
            n_iterations=self.n_iterations + other.n_iterations,
        )

    def __radd__(self, other: Elapsed | int) -> Elapsed:
        return self + other

    def __str__(self) -> str:
        return f"{format_time_duration(self.t_elapsed_sec, n_chars=6, pad=False)} ({self.n_iterations:_} iterations)"


__ALL__ = [
    "TargetDuration",
    "TargetTotalTimeDuration",
    "ProgressTracker",
    "Progress",
    "Elapsed",
    "iterations",
    "seconds",
    "minutes",
    "hours",
    "total_seconds",
    "total_minutes",
    "total_hours",
]
