from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from functools import cached_property
from typing import TYPE_CHECKING

import numpy as np

from max_div._core.constraints import Constraint, ConstraintList

from ._score import Score, ScoreGenerator
from ._signals import build_tracker

if TYPE_CHECKING:
    from numpy.typing import NDArray

    from max_div._core.metrics import DiversityMetric, DiversitySignalFamily

    from ._signals import DiversitySignalTracker


# =================================================================================================
#  Solver State
# =================================================================================================
class SolverState:
    """Abstract base class for solver state management."""

    # -------------------------------------------------------------------------
    #  Construction & Configuration
    # -------------------------------------------------------------------------
    def __init__(
        self,
        n: np.int32,
        k: np.int32,
        signal_trackers: dict[DiversitySignalFamily, DiversitySignalTracker],
        main_signal_family: DiversitySignalFamily,
        score_generator: ScoreGenerator,
        selected: NDArray[np.bool],
        con_values: NDArray[np.int32],
        con_indices: NDArray[np.int32],
        con_membership: dict[np.int32, NDArray[np.int32]],
    ) -> None:
        """Initialize the SolverState.  The constructor is not intended to be used directly, instead use new().

        Problem Dimensions:

            n  : total number of vectors
          ( d  : dimensionality of each vector  (not visible here, since distances are pre-digested
                 into the signal trackers) )
            k  : target selection size
            m : number of constraints

        :param n: (np.int32) number of vectors
        :param k: (np.int32) target number of selected vectors
        :param signal_trackers: (dict[DiversitySignalFamily, DiversitySignalTracker]) per-point diversity-signal
                                tracking, one tracker per signal family needed by the configured metrics; all are
                                incrementally updated on every selection mutation.  Trackers of families no metric
                                needs are simply absent, so their maintenance costs nothing.
        :param main_signal_family: (DiversitySignalFamily) family of the main diversity metric; its tracker feeds
                                   the strategy-facing signal properties.
        :param score_generator: (ScoreGenerator) score generator to compute scores for current state
        :param selected: (np.ndarray[np.bool]) array indicating which of the n vectors are initially selected.
        :param con_values: (np.ndarray[np.int32] | None) upper/lower bounds per constraint (m x 2 array of float32)
                                                                     (as generated by _build_array_repr)
        :param con_indices: (np.ndarray[np.int32] | None) 1d array with all indices per constraint
                                                                     (as generated by _build_array_repr)
        :param con_membership: (dict[np.int32, NDArray[np.int32]] | None) mapping from index to its constraints
                                                                     (as generated by _build_con_membership)
        """
        self._n = n  # READ-ONLY
        self._k = k  # READ-ONLY

        # diversity signals
        self._signal_trackers_by_family = signal_trackers  # READ-ONLY
        self._main_signal_family = main_signal_family  # READ-ONLY
        self._signal_trackers = tuple(signal_trackers.values())  # iteration order for mutations
        self._signal_tracker = signal_trackers[main_signal_family]  # strategy-facing tracker

        # scoring
        self._score_generator = score_generator  # READ-ONLY
        self._score: Score | None = None
        self._score_dirty: bool = False  # when True, _score is stale and recomputed on next 'score' read

        # selection
        self._selected = selected
        self._n_selected: np.int32 = np.int32(selected.sum())

        # constraints
        self._con_values = con_values  # min/max counts of extra samples needed on top of current selection
        self._con_indices = con_indices  # READ-ONLY
        self._con_membership = con_membership  # READ-ONLY

        # snapshot
        self._snapshot: Snapshot = Snapshot.empty()

        # finalize
        self._update_score()

    # -------------------------------------------------------------------------
    #  Copy
    # -------------------------------------------------------------------------
    def copy(self) -> SolverState:
        """Returns a deep copy of the current state."""
        return SolverState(
            n=self._n,
            k=self._k,
            signal_trackers={family: t.copy() for family, t in self._signal_trackers_by_family.items()},
            main_signal_family=self._main_signal_family,
            score_generator=self._score_generator.copy(),
            selected=self._selected.copy(),
            con_values=self._con_values.copy(),
            con_indices=self._con_indices.copy(),
            con_membership=deepcopy(self._con_membership),
        )

    # -------------------------------------------------------------------------
    #  Main API - used by solver strategies to modify state
    # -------------------------------------------------------------------------
    def set_snapshot(self) -> None:
        """Internally saves the current state as a snapshot (possibly overwriting any previous snapshot).

        Such a snapshot can be restored using the restore_snapshot() method, with any actions that happened
        in between (add, remove) being undone.
        """
        # NOTE: we create copies, such that add(.) and remove(.) cannot influence the snapshot after it was taken
        self._snapshot.selected = self._selected.copy()
        self._snapshot.n_selected = self._n_selected
        self._snapshot.con_values = self._con_values.copy()
        for tracker in self._signal_trackers:
            tracker.set_snapshot()
        # NOTE: Score is immutable and mutators reassign self._score (never modify in place),
        #       so storing the reference is safe — no copy needed.
        self._snapshot.score = self.score
        self._snapshot.is_valid = True

    def restore_snapshot(self) -> None:
        """Restores the state of this object to the state saved in the last call to set_snapshot().

        Any actions that happened in between (add, remove) are undone.  If set_snapshot() hasn't been called before,
        a ValueError is raised.  After restoring the snapshot, it gets cleared, such that subsequent calls to
        restore_snapshot() without an intermediate call to set_snapshot() will again raise a ValueError.
        """
        if not self._snapshot.is_valid:
            raise ValueError("Cannot restore snapshot: set_snapshot() not called before.")

        # restore snapshot (no copy needed; we will clear the snapshot)
        self._selected = self._snapshot.selected
        self._n_selected = self._snapshot.n_selected
        self._con_values = self._snapshot.con_values
        for tracker in self._signal_trackers:
            tracker.restore_snapshot()

        # restore score (cached at set_snapshot time; avoids a full recompute)
        self._score = self._snapshot.score
        self._score_dirty = False

        # clear snapshot after restoring
        self._snapshot.clear()

    def add(self, index: int | np.int32) -> None:
        # --- validation ----------------------------------
        index = np.int32(index)
        if self._selected[index]:
            raise ValueError(f"Cannot add index that is already selected ({index}).")

        # --- selection -----------------------------------
        self._selected[index] = True
        self._n_selected += np.int32(1)

        # --- diversity signals ---------------------------
        for tracker in self._signal_trackers:
            tracker.add(index)

        # --- constraints ---------------------------------
        # decrease both min_count and max_count for all constraints that include 'index'
        self._con_values[self._con_membership[index], :] -= 1

        # --- score ---------------------------------------
        self._score_dirty = True

    def add_many(self, indices: NDArray[np.int32]) -> None:
        # --- validation ----------------------------------
        if self._selected[indices].any():
            raise ValueError(f"Cannot add index that is already selected ({list(indices)}).")

        # --- selection -----------------------------------
        self._selected[indices] = True
        self._n_selected += np.int32(len(indices))

        # --- diversity signals ---------------------------
        for tracker in self._signal_trackers:
            tracker.add_many(indices)

        # --- constraints ---------------------------------
        # decrease both min_count and max_count for all constraints that include any of 'indices'
        for index in indices:
            self._con_values[self._con_membership[index], :] -= 1

        # --- score ---------------------------------------
        self._score_dirty = True

    def remove(self, index: int | np.int32) -> None:
        # --- validation ----------------------------------
        index = np.int32(index)
        if not self._selected[index]:
            raise ValueError(f"Cannot remove index that is not selected ({index}).")

        # --- selection -----------------------------------
        self._selected[index] = False
        self._n_selected -= np.int32(1)

        # --- diversity signals ---------------------------
        new_selection = self.selected_index_array
        for tracker in self._signal_trackers:
            tracker.remove(index, new_selection)

        # --- constraints ---------------------------------
        # increase both min_count and max_count for all constraints that include 'index'
        self._con_values[self._con_membership[index], :] += 1

        # --- score ---------------------------------------
        self._score_dirty = True

    def remove_many(self, indices: NDArray[np.int32]) -> None:
        # --- validation ----------------------------------
        if (~self._selected[indices]).any():
            raise ValueError(f"Cannot remove index that is not selected ({list(indices)}).")

        # --- selection -----------------------------------
        self._selected[indices] = False
        self._n_selected -= np.int32(len(indices))

        # --- diversity signals ---------------------------
        new_selection = self.selected_index_array
        for tracker in self._signal_trackers:
            tracker.remove_many(indices, new_selection)

        # --- constraints ---------------------------------
        # increase both min_count and max_count for all constraints that include any of 'indices'
        for index in indices:
            self._con_values[self._con_membership[index], :] += 1

        # --- score ---------------------------------------
        self._score_dirty = True

    # -------------------------------------------------------------------------
    #  Properties
    # -------------------------------------------------------------------------
    @cached_property
    def n(self) -> np.int32:
        """Return total number of vectors."""
        return self._n

    @cached_property
    def k(self) -> np.int32:
        """Return target selection size."""
        return self._k

    @property
    def n_selected(self) -> np.int32:
        """Return current number of selected vectors."""
        return self._n_selected

    @property
    def n_not_selected(self) -> np.int32:
        """Return current number of selected vectors."""
        return self._n - self._n_selected

    @cached_property
    def m(self) -> np.int32:
        """Return total number of constraints."""
        return self._con_values.shape[0]

    @cached_property
    def has_constraints(self) -> bool:
        """Return True if >0 constraints are defined."""
        return self._con_values.shape[0] > 0

    @cached_property
    def con_indices(self) -> NDArray[np.int32]:
        """Return constraint indices array."""
        return self._con_indices  # should not be modified (!)

    @property  # not cached, since this array is expected to change
    def con_values(self) -> NDArray[np.int32]:
        """Return constraint indices array."""
        return self._con_values  # should not be modified (!)

    @property
    def selected_index_array(self) -> NDArray[np.int32]:
        """Return selected indices as a numpy array of np.int32."""
        return np.flatnonzero(self._selected).astype(np.int32)

    @property
    def not_selected_index_array(self) -> NDArray[np.int32]:
        """Return not selected indices as a numpy array of np.int32."""
        return np.flatnonzero(~self._selected).astype(np.int32)

    @property
    def selected_signal_array(self) -> NDArray[np.float32]:
        """Return diversity signal of selected vectors wrt the current selection as a numpy array of np.float32."""
        return self._signal_tracker.full_signal(self._selected, self._n_selected)[self._selected]

    @property
    def not_selected_signal_array(self) -> NDArray[np.float32]:
        """Return diversity signal of not selected vectors wrt the current selection as a numpy array of np.float32."""
        return self._signal_tracker.full_signal(self._selected, self._n_selected)[~self._selected]

    @property
    def full_signal_array(self) -> NDArray[np.float32]:
        """Return diversity signal of all vectors wrt the current selection as a numpy array of np.float32."""
        return self._signal_tracker.full_signal(self._selected, self._n_selected)  # should not be modified (!)

    @property
    def global_signal_array(self) -> NDArray[np.float32]:
        """Return static diversity signal of all vectors wrt the whole dataset as a numpy array of np.float32."""
        return self._signal_tracker.global_signal  # should not be modified (!)

    # -------------------------------------------------------------------------
    #  Scoring
    # -------------------------------------------------------------------------
    def _update_score(self) -> None:
        self._score = self._score_generator.compute_score(
            n_selected=self._n_selected,
            con_values=self._con_values,
            selected_separation_array=self.selected_signal_array,
        )
        self._score_dirty = False

    @property
    def score(self) -> Score:
        """Return overall score of the current selection as a multi-component prioritized Score object."""
        if self._score_dirty:
            self._update_score()
        return self._score  # ty: ignore[invalid-return-type]  # always set via _update_score in __init__; hot path, so no assert

    # -------------------------------------------------------------------------
    #  Factory methods
    # -------------------------------------------------------------------------
    @classmethod
    def new(
        cls,
        n: int,
        pdist: NDArray[np.float32],
        k: int,
        diversity_metric: DiversityMetric,
        diversity_tie_breakers: list[DiversityMetric],
        constraints: list[Constraint],
        penalty_quadratic: bool = False,
    ) -> SolverState:
        # --- diversity signals ---
        # one tracker per signal family needed by the configured metrics (main metric's family first,
        # so the strategy-facing tracker is always present); unneeded families are never constructed
        n_np = np.int32(n)
        main_signal_family = diversity_metric.signal_family
        families = dict.fromkeys([main_signal_family, *(tb.signal_family for tb in diversity_tie_breakers)])
        signal_trackers = {family: build_tracker(family, pdist, n_np) for family in families}

        # --- selection ---
        selected = np.full(n_np, False, dtype=np.bool)

        # --- constraints ---
        con_values, con_indices = ConstraintList(constraints).to_numpy()
        con_membership = _build_con_membership(n_np, constraints)

        # --- score generator ---
        score_generator = ScoreGenerator(
            n=n_np,
            k=k,
            diversity_metric=diversity_metric,
            diversity_tie_breakers=diversity_tie_breakers,
            constraints=constraints,
            penalty_quadratic=penalty_quadratic,
        )

        # --- construct & return ---
        return SolverState(
            n=n_np,
            k=np.int32(k),
            signal_trackers=signal_trackers,
            main_signal_family=main_signal_family,
            score_generator=score_generator,
            selected=selected,
            con_values=con_values,
            con_indices=con_indices,
            con_membership=con_membership,
        )


# =================================================================================================
#  Helper Classes
# =================================================================================================
@dataclass(slots=True)
class Snapshot:
    """Class internally used by SolverState to store snapshots of its state.

    This class models a subset of the fields of the SolverState class, restricting itself to those that can be
    modified after construction.  Diversity-signal state is snapshotted by the signal tracker itself, in lockstep
    with this snapshot's life cycle.
    """

    is_valid: bool

    selected: NDArray[np.bool]  # boolean array representing the selection
    n_selected: np.int32  # number of True values in 'selected'

    con_values: NDArray[np.int32]  # (nc x 2)-sized array with current status of constraint bounds

    score: Score  # score of the snapshotted selection (immutable, stored by reference)

    # -------------------------------------------------------------------------
    #  Modification / Factory
    # -------------------------------------------------------------------------
    def clear(self) -> None:
        """Clear the snapshot, making it invalid."""
        self.is_valid = False
        self.selected = _EMPTY_NP_ARRAY_BOOL
        self.n_selected = np.int32(0)
        self.con_values = _EMPTY_NP_ARRAY_INT32
        self.score = _PLACEHOLDER_SCORE

    @classmethod
    def empty(cls) -> Snapshot:
        """Create and return an empty/invalid snapshot."""
        return Snapshot(
            is_valid=False,
            selected=_EMPTY_NP_ARRAY_BOOL,
            n_selected=np.int32(0),
            con_values=_EMPTY_NP_ARRAY_INT32,
            score=_PLACEHOLDER_SCORE,
        )


# singletons to avoid repeated, unnecessary allocations
# (an invalid snapshot's score is never read — restore_snapshot guards on is_valid)
_EMPTY_NP_ARRAY_BOOL = np.array([], dtype=np.bool)
_EMPTY_NP_ARRAY_INT32 = np.array([], dtype=np.int32)
_PLACEHOLDER_SCORE = Score(size=0.0, constraints=0.0, diversity=0.0, div_tie_breakers=())


# =================================================================================================
#  HELPERS
# =================================================================================================
def _build_con_membership(
    m: np.int32,
    constraints: list[Constraint],
) -> dict[np.int32, NDArray[np.int32]]:
    """Build a mapping from each index to the list of constraints it belongs to."""
    # map index -> list
    con_membership_lst: dict[np.int32, list[np.int32]] = {i: [] for i in np.arange(m, dtype=np.int32)}
    for i_con, con in enumerate(constraints):
        i_con_np = np.int32(i_con)
        for idx in con.int_set:
            con_membership_lst[np.int32(idx)].append(i_con_np)

    # map index -> np.array
    return {idx: np.array(con_list, dtype=np.int32) for idx, con_list in con_membership_lst.items()}
