from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property
from typing import TYPE_CHECKING

import numpy as np

from max_div._core._math import select_k_max_masked
from max_div._core._utils import delete_sorted, insert_sorted
from max_div._core.constraints import Constraint, ConstraintList, _np_con_membership, to_numpy_membership

from ._diversity_contribution import DiversityContributionTrackers
from ._score import Score, ScoreGenerator

if TYPE_CHECKING:
    from numpy.typing import NDArray

    from max_div._core.metrics import DiversityMetric
    from max_div._core.metrics._distance import DistanceStore


# =================================================================================================
#  Solver State
# =================================================================================================
class SolverState:
    """Mutable state of a solver run: selection, constraint status, diversity contributions, and score.

    Savepoint mechanics:

        Provisional changes are managed by three fields that always move together:

            _depth       number of currently open scopes
            _snapshots   entries 0.._depth-1 hold the state saved at each open scope, innermost
                         last; entries at _depth and above are cleared spares kept for reuse
            _savepoints  the scope object handed out at each depth, one per depth ever reached

        Both lists only ever grow: reaching a depth for the first time appends its entry, every
        later visit reuses it, so steady-state operation allocates nothing.  A nested trial
        evolves like this:

            with state.savepoint():      # depth 0 -> 1: state saved into _snapshots[0]
                ...
                with state.savepoint():  # depth 1 -> 2: state saved into _snapshots[1]
                    ...
                # inner exit             # depth 2 -> 1: state restored from _snapshots[1],
                                         #   or left as-is (kept); either way _snapshots[1]
                                         #   is cleared back to a spare
            # outer exit                 # depth 1 -> 0: same, against _snapshots[0]

        Keeping and restoring thus leave the lists themselves identical — they differ only in
        whether the state was first restored from the top entry before that entry was cleared.
    """

    # -------------------------------------------------------------------------
    #  Construction & Configuration
    # -------------------------------------------------------------------------
    def __init__(
        self,
        n: np.int32,
        k: np.int32,
        contribution_trackers: DiversityContributionTrackers,
        score_generator: ScoreGenerator,
        selected: NDArray[np.bool],
        con_values: NDArray[np.int32],
        con_indices: NDArray[np.int32],
        con_weights: NDArray[np.float64],
        con_membership: NDArray[np.int32] | None,
    ) -> None:
        """Initialize the SolverState.  The constructor is not intended to be used directly, instead use new().

        Problem Dimensions:

            n  : total number of items
          ( d  : dimensionality of each vector  (not visible here, since distances are pre-digested
                 into the contribution trackers) )
            k  : target selection size
            m : number of constraints

        Args:
            n: (np.int32) number of items
            k: (np.int32) target number of selected items
            contribution_trackers: (DiversityContributionTrackers) the tracker set backing this state's
                per-point diversity contributions, updated on every selection mutation.
            score_generator: (ScoreGenerator) score generator to compute scores for current state
            selected: (np.ndarray[np.bool]) array indicating which of the n items are initially selected.
            con_values: (np.ndarray[np.int32] | None) upper/lower bounds per constraint (m x 2 array of float32)
                (as generated by _build_array_repr)
            con_indices: (np.ndarray[np.int32] | None) 1d array with all indices per constraint
                (as generated by _build_array_repr)
            con_weights: (np.ndarray[np.float64]) per-constraint violation weights, in constraint order
            con_membership: (np.ndarray[np.int32] | None) packed mapping from index to its constraints
                (as generated by to_numpy_membership); None when the problem has no constraints, so an
                unconstrained state carries no per-item bookkeeping
        """
        self._n = n  # READ-ONLY
        self._k = k  # READ-ONLY

        # diversity contributions
        self._contribution_trackers = contribution_trackers
        self._contribution_tracker = contribution_trackers.main  # strategy-facing tracker (cached hop)

        # scoring
        self._score_generator = score_generator  # READ-ONLY
        self._score: Score | None = None
        self._score_dirty: bool = False  # when True, _score is stale and recomputed on next 'score' read

        # selection
        self._selected = selected
        self._n_selected: np.int32 = np.int32(selected.sum())
        # The same selection as an ascending index list, kept in step with the mask above.  The
        # ascending order is load-bearing: candidates are drawn from this list *by position*, so a
        # different order selects different items.
        self._selected_indices = np.empty(len(selected), dtype=np.int32)
        self._selected_indices[: self._n_selected] = np.flatnonzero(selected)

        # constraints
        self._con_values = con_values  # min/max counts of extra samples needed on top of current selection
        self._con_indices = con_indices  # READ-ONLY
        self._con_weights = con_weights  # READ-ONLY
        self._con_membership = con_membership  # READ-ONLY

        # snapshots — a stack, so provisional changes can nest ("Savepoint mechanics" in the class docstring)
        self._snapshots: list[Snapshot] = []
        self._savepoints: list[Savepoint] = []
        self._depth: int = 0

        # finalize
        self._update_score()

    # -------------------------------------------------------------------------
    #  Copy
    # -------------------------------------------------------------------------
    def copy(self) -> SolverState:
        """Return an independent copy of the state; the read-only membership array is shared, not duplicated."""
        return SolverState(
            n=self._n,
            k=self._k,
            contribution_trackers=self._contribution_trackers.copy(),
            score_generator=self._score_generator.copy(),
            selected=self._selected.copy(),
            con_values=self._con_values.copy(),
            con_indices=self._con_indices.copy(),
            con_weights=self._con_weights.copy(),
            con_membership=self._con_membership,  # shared, not copied: read-only for the state's lifetime
        )

    # -------------------------------------------------------------------------
    #  Main API - used by solver strategies to modify state
    # -------------------------------------------------------------------------
    def savepoint(self) -> Savepoint:
        """Open a scope in which every change to this state is provisional.

        On leaving the scope the pre-scope state is restored, unless the scope was explicitly kept:

            with state.savepoint() as sp:   # everything in here is provisional
                state.remove(i)
                if state.score > best:
                    sp.keep()               # ... unless we say otherwise

        Restoring is the default, so a trial reads as nothing more than a `with` block, and an
        exception inside the scope leaves the state untouched.  Scopes nest: the solver evaluates
        candidates provisionally inside a swap that is itself provisional.
        """
        depth = self._depth
        if depth == len(self._savepoints):
            # first time this nesting depth is reached: allocate its scope object; later visits reuse it
            self._savepoints.append(Savepoint(self))
        return self._savepoints[depth]

    def _push_snapshot(self) -> None:
        """Save the current state on top of the snapshot stack."""
        depth = self._depth
        if depth == len(self._snapshots):
            # first time this nesting depth is reached: allocate its entry; later visits refill the spare in place
            self._snapshots.append(Snapshot.empty())
        snapshot = self._snapshots[depth]

        # NOTE: we create copies, such that add(.) and remove(.) cannot influence the snapshot after it was taken
        snapshot.selected = self._selected.copy()
        snapshot.n_selected = self._n_selected
        snapshot.selected_indices = self._selected_indices[: self._n_selected].copy()
        snapshot.con_values = self._con_values.copy()
        self._contribution_trackers.push_snapshot()
        # NOTE: Score is immutable and mutators reassign self._score (never modify in place),
        #       so storing the reference is safe — no copy needed.
        snapshot.score = self.score

        self._depth = depth + 1

    def _pop_snapshot(self, restore: bool) -> None:
        """Discard the top snapshot, first restoring this state from it if `restore`."""
        depth = self._depth - 1
        snapshot = self._snapshots[depth]
        self._contribution_trackers.pop_snapshot(restore)

        if restore:
            # no copy needed; the snapshot is cleared below, so the restored arrays cannot alias a live snapshot
            self._selected = snapshot.selected
            self._n_selected = snapshot.n_selected
            # written back into the buffer rather than rebound, so it keeps its full capacity
            self._selected_indices[: snapshot.n_selected] = snapshot.selected_indices
            self._con_values = snapshot.con_values

            # restore score (cached at push time; avoids a full recompute)
            self._score = snapshot.score
            self._score_dirty = False

        snapshot.clear()
        self._depth = depth

    def _insert_selected_index(self, index: np.int32) -> None:
        """Insert `index` into the ascending index list; call before `_n_selected` grows."""
        insert_sorted(self._selected_indices, self._n_selected, index)

    def _delete_selected_index(self, index: np.int32) -> None:
        """Remove `index` from the ascending index list; call before `_n_selected` shrinks."""
        delete_sorted(self._selected_indices, self._n_selected, index)

    # The four mutation methods below leave their range and duplicate preconditions UNCHECKED:
    # they run every swap iteration, so enforcement lives in the strategies' tests (which pin
    # that emitted batches are in range and duplicate-free), not in runtime code.
    def add(self, index: int | np.int32) -> None:
        """Add `index` to the selection; it must be in `[0, n)` and not already selected."""
        # --- validation -------------------------
        index = np.int32(index)
        if self._selected[index]:
            raise ValueError(f"Cannot add index that is already selected ({index}).")

        # --- selection --------------------------
        self._selected[index] = True
        self._insert_selected_index(index)
        self._n_selected += np.int32(1)

        # --- diversity contributions ------------
        self._contribution_trackers.add(index)

        # --- constraints ------------------------
        # decrease both min_count and max_count for all constraints that include 'index'
        if self._con_membership is not None:
            self._con_values[_np_con_membership(self._con_membership, index), :] -= 1

        # --- score ------------------------------
        self._score_dirty = True

    def add_many(self, indices: NDArray[np.int32], parallel: bool = False) -> None:
        """Add all of `indices` to the selection; they must be in `[0, n)`, duplicate-free, and not selected.

        A duplicate would desynchronize `n_selected` from the mask; `adopt_selection` is the
        entry point that dedups for you.  `parallel` lets the contribution trackers update over
        parallel threads (identical results; see the tracker base class for when to opt in).
        """
        # --- validation -------------------------
        if self._selected[indices].any():
            raise ValueError(f"Cannot add index that is already selected ({list(indices)}).")

        # --- selection --------------------------
        self._selected[indices] = True
        # the count advances inside the loop because each insert reads it as the list's current
        # length; raising it once afterwards would give every insert but the first a stale length
        for index in indices:
            self._insert_selected_index(index)
            self._n_selected += np.int32(1)

        # --- diversity contributions ------------
        self._contribution_trackers.add_many(indices, parallel=parallel)

        # --- constraints ------------------------
        # decrease both min_count and max_count for all constraints that include any of 'indices'
        if self._con_membership is not None:
            for index in indices:
                self._con_values[_np_con_membership(self._con_membership, index), :] -= 1

        # --- score ------------------------------
        self._score_dirty = True

    def remove(self, index: int | np.int32) -> None:
        """Remove `index` from the selection; it must be in `[0, n)` and currently selected."""
        # --- validation -------------------------
        index = np.int32(index)
        if not self._selected[index]:
            raise ValueError(f"Cannot remove index that is not selected ({index}).")

        # --- selection --------------------------
        self._selected[index] = False
        self._delete_selected_index(index)
        self._n_selected -= np.int32(1)

        # --- diversity contributions ------------
        self._contribution_trackers.remove(index, self.selected_index_array)

        # --- constraints ------------------------
        # increase both min_count and max_count for all constraints that include 'index'
        if self._con_membership is not None:
            self._con_values[_np_con_membership(self._con_membership, index), :] += 1

        # --- score ------------------------------
        self._score_dirty = True

    def remove_many(self, indices: NDArray[np.int32]) -> None:
        """Remove all of `indices` from the selection; they must be in `[0, n)`, duplicate-free, and selected.

        A duplicate passes the is-selected check yet reaches `delete_sorted` a second time with
        an absent value.
        """
        # --- validation -------------------------
        if (~self._selected[indices]).any():
            raise ValueError(f"Cannot remove index that is not selected ({list(indices)}).")

        # --- selection --------------------------
        self._selected[indices] = False
        # same reason as in add_many: each delete reads the count as the list's current length
        for index in indices:
            self._delete_selected_index(index)
            self._n_selected -= np.int32(1)

        # --- diversity contributions ------------
        self._contribution_trackers.remove_many(indices, self.selected_index_array)

        # --- constraints ------------------------
        # increase both min_count and max_count for all constraints that include any of 'indices'
        if self._con_membership is not None:
            for index in indices:
                self._con_values[_np_con_membership(self._con_membership, index), :] += 1

        # --- score ------------------------------
        self._score_dirty = True

    def reset(self) -> None:
        """Return the state to the empty selection, updating all incremental state to match.

        Cheaper than removing the selected items one by one: the trackers jump straight to their
        empty-selection values instead of rescanning after every removal.

        Raises:
            RuntimeError: If a savepoint is open — a reset cannot be provisional.
        """
        # --- validation -------------------------
        if self._depth != 0:
            raise RuntimeError("Cannot reset the selection while a savepoint is open.")

        # --- constraints ------------------------
        # undo the constraint effect of the current selection while its index view is intact
        if self._con_membership is not None:
            for index in self.selected_index_array:
                self._con_values[_np_con_membership(self._con_membership, index), :] += 1

        # --- selection --------------------------
        self._selected.fill(False)
        self._n_selected = np.int32(0)

        # --- diversity contributions ------------
        self._contribution_trackers.reset()

        # --- score ------------------------------
        self._score_dirty = True

    def adopt_selection(self, indices: NDArray[np.int32]) -> None:
        """Replace the current selection with `indices`, updating all incremental state to match.

        Adoption installs a selection produced elsewhere (e.g. another worker's published best) as if it
        had been built through this state's own mutators, applying the cheaper of a selection diff
        or a reset-then-rebuild.

        Args:
            indices: (int32 ndarray) the selection to adopt; duplicate-free, any order.

        Raises:
            RuntimeError: If a savepoint is open — an adoption cannot be provisional.
            ValueError: If `indices` contains duplicates or out-of-range values.
        """
        # --- validation -------------------------
        if self._depth != 0:
            raise RuntimeError("Cannot adopt a selection while a savepoint is open.")
        foreign = np.unique(np.asarray(indices, dtype=np.int32))  # ascending, deduplicated
        if foreign.size != len(indices):
            raise ValueError(f"Cannot adopt a selection with duplicate indices ({list(indices)}).")
        if foreign.size > 0 and (foreign[0] < 0 or foreign[-1] >= self._n):
            raise ValueError(f"Cannot adopt a selection with out-of-range indices ({list(indices)}).")

        # --- route selection --------------------
        current = self.selected_index_array
        to_remove = np.setdiff1d(current, foreign, assume_unique=True)
        to_add = np.setdiff1d(foreign, current, assume_unique=True)

        if to_remove.size + to_add.size <= foreign.size:
            # --- diff route ---------------------
            self.remove_many(to_remove)
            self.add_many(to_add)
        else:
            # --- rebuild route ------------------
            self.reset()
            self.add_many(foreign)

    # -------------------------------------------------------------------------
    #  Properties
    # -------------------------------------------------------------------------
    @cached_property
    def n(self) -> np.int32:
        """Return total number of items."""
        return self._n

    @cached_property
    def k(self) -> np.int32:
        """Return target selection size."""
        return self._k

    @property
    def n_selected(self) -> np.int32:
        """Return current number of selected items."""
        return self._n_selected

    @property
    def n_not_selected(self) -> np.int32:
        """Return current number of selected items."""
        return self._n - self._n_selected

    @cached_property
    def m(self) -> np.int32:
        """Return total number of constraints."""
        return self._con_values.shape[0]

    @cached_property
    def has_constraints(self) -> bool:
        """Return True if >0 constraints are defined."""
        return self._con_values.shape[0] > 0

    @cached_property
    def con_indices(self) -> NDArray[np.int32]:
        """Return constraint indices array."""
        return self._con_indices  # should not be modified (!)

    @property  # not cached, since this array is expected to change
    def con_values(self) -> NDArray[np.int32]:
        """Return constraint indices array."""
        return self._con_values  # should not be modified (!)

    @cached_property
    def con_weights(self) -> NDArray[np.float64]:
        """Return the per-constraint violation weights, in constraint order."""
        return self._con_weights  # should not be modified (!)

    @property
    def selected_index_array(self) -> NDArray[np.int32]:
        """Return the selected indices, ascending (reference; do not modify)."""
        return self._selected_indices[: self._n_selected]

    @property
    def distance_store(self) -> DistanceStore:
        """Return the distance store backing this state's trackers (shared, immutable)."""
        return self._contribution_tracker.store

    def top_not_selected_contributions(self, m: int | np.int32) -> tuple[NDArray[np.int32], NDArray[np.float32]]:
        """Return indices and contributions of the up-to-m not-selected items with the highest contribution.

        Both arrays are freshly allocated (safe for in-place mutation by the caller); fewer than
        m items come back when fewer are not selected.
        """
        contributions = self.full_contribution_array
        indices = select_k_max_masked(contributions, np.int32(m), self._selected)
        return indices, contributions[indices]

    @property
    def not_selected_index_array(self) -> NDArray[np.int32]:
        """Return not selected indices as a numpy array of np.int32."""
        return np.flatnonzero(~self._selected).astype(np.int32)

    @property
    def selected_contribution_array(self) -> NDArray[np.float32]:
        """Return diversity contribution of selected items wrt the current selection (np.float32 ndarray)."""
        return self._contribution_tracker.contribution_wrt_selection(self._selected, self._n_selected)[
            self.selected_index_array
        ]

    @property
    def not_selected_contribution_array(self) -> NDArray[np.float32]:
        """Return diversity contribution of not selected items wrt the current selection (np.float32 ndarray)."""
        return self._contribution_tracker.contribution_wrt_selection(self._selected, self._n_selected)[~self._selected]

    @property
    def full_contribution_array(self) -> NDArray[np.float32]:
        """Return diversity contribution of all items wrt the current selection (np.float32 ndarray)."""
        return self._contribution_tracker.contribution_wrt_selection(
            self._selected, self._n_selected
        )  # should not be modified (!)

    @property
    def global_contribution_array(self) -> NDArray[np.float32]:
        """Return static diversity contribution of all items wrt the whole dataset (np.float32 ndarray).

        Accessing this computes any not-yet-computed entries first (the full O(n²) sweep on first
        access); callers needing only some entries use `global_contribution_for`.
        """
        return self._contribution_tracker.contribution_wrt_dataset  # should not be modified (!)

    def global_contribution_for(self, indices: NDArray[np.int32]) -> NDArray[np.float32]:
        """Return dataset-wide contributions for `indices`, computing missing entries first.

        Returns a freshly allocated array (safe for in-place mutation by the caller); cost is
        proportional to the not-yet-computed elements among `indices` rather than to n.
        """
        return self._contribution_tracker.contribution_wrt_dataset_for(indices)

    # -------------------------------------------------------------------------
    #  Scoring
    # -------------------------------------------------------------------------
    def _update_score(self) -> None:
        self._score = self._score_generator.compute_score(
            n_selected=self._n_selected,
            con_values=self._con_values,
            selected_contributions=self._contribution_trackers.selected_contributions(
                self._selected, self._n_selected, self.selected_index_array
            ),
        )
        self._score_dirty = False

    @property
    def score(self) -> Score:
        """Return overall score of the current selection as a multi-component prioritized Score object."""
        if self._score_dirty:
            self._update_score()
        return self._score  # ty: ignore[invalid-return-type]  # always set via _update_score in __init__; hot path, so no assert

    # -------------------------------------------------------------------------
    #  Factory methods
    # -------------------------------------------------------------------------
    @classmethod
    def new(
        cls,
        n: int,
        store: DistanceStore,
        k: int,
        diversity_metric: DiversityMetric,
        diversity_tie_breakers: list[DiversityMetric],
        constraints: list[Constraint],
        penalty_quadratic: bool = False,
    ) -> SolverState:
        # --- diversity contributions ------------
        n_np = np.int32(n)
        contribution_trackers = DiversityContributionTrackers.for_metrics(
            diversity_metric, diversity_tie_breakers, store
        )

        # --- selection --------------------------
        selected = np.full(n_np, False, dtype=np.bool)

        # --- constraints ------------------------
        con_values, con_indices = ConstraintList(constraints).to_numpy()
        con_weights = np.array([con.weight for con in constraints], dtype=np.float64)
        con_membership = to_numpy_membership(con_indices, m=len(constraints), n=n) if constraints else None

        # --- score generator --------------------
        score_generator = ScoreGenerator(
            n=n_np,
            k=k,
            diversity_metric=diversity_metric,
            diversity_tie_breakers=diversity_tie_breakers,
            constraints=constraints,
            penalty_quadratic=penalty_quadratic,
        )

        # --- construct & return -----------------
        return SolverState(
            n=n_np,
            k=np.int32(k),
            contribution_trackers=contribution_trackers,
            score_generator=score_generator,
            selected=selected,
            con_values=con_values,
            con_indices=con_indices,
            con_weights=con_weights,
            con_membership=con_membership,
        )


# =================================================================================================
#  Helper Classes
# =================================================================================================
class Savepoint:
    """Scope over provisional changes to a SolverState; see SolverState.savepoint().

    Written as a class with __enter__/__exit__ rather than a @contextmanager generator: the solver
    enters one of these tens of times per iteration, and generator-based context managers cost
    noticeably more per entry.  One instance is reused per nesting depth, so entering a scope
    allocates nothing.
    """

    __slots__ = ("_keep", "_state")

    def __init__(self, state: SolverState) -> None:
        """Bind the scope to its state.  Not intended to be constructed directly."""
        self._state = state
        self._keep = False

    def keep(self) -> None:
        """Keep the changes made inside this scope instead of restoring the pre-scope state on exit."""
        self._keep = True

    def __enter__(self) -> Savepoint:
        """Snapshot the state, so everything until __exit__ can be undone."""
        self._keep = False  # this object is reused across scopes; never inherit the previous outcome
        self._state._push_snapshot()  # noqa: SLF001 -- Savepoint is SolverState's own scope object
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> bool:  # noqa: ANN001 -- standard context-manager signature
        """Restore the pre-scope state unless the scope was kept; an exception always restores and always propagates."""
        self._state._pop_snapshot(restore=not self._keep or exc_type is not None)  # noqa: SLF001 -- as above
        return False  # never swallow an exception


@dataclass(slots=True)
class Snapshot:
    """Class internally used by SolverState to store snapshots of its state.

    This class models a subset of the fields of the SolverState class, restricting itself to those that can be
    modified after construction.  Diversity-contribution state is snapshotted by the contribution trackers
    themselves, in lockstep with this snapshot's life cycle.
    """

    selected: NDArray[np.bool]  # boolean array representing the selection
    n_selected: np.int32  # number of True values in 'selected'
    selected_indices: NDArray[np.int32]  # the same selection, ascending; a copy of the live prefix

    con_values: NDArray[np.int32]  # (nc x 2)-sized array with current status of constraint bounds

    score: Score  # score of the snapshotted selection (immutable, stored by reference)

    # -------------------------------------------------------------------------
    #  Modification / Factory
    # -------------------------------------------------------------------------
    def clear(self) -> None:
        """Release the state held by this snapshot, returning it to the spare pool."""
        self.selected = _EMPTY_NP_ARRAY_BOOL
        self.n_selected = np.int32(0)
        self.selected_indices = _EMPTY_NP_ARRAY_INT32
        self.con_values = _EMPTY_NP_ARRAY_INT32
        self.score = _PLACEHOLDER_SCORE

    @classmethod
    def empty(cls) -> Snapshot:
        """Create and return a cleared snapshot, ready to be filled by a push."""
        return Snapshot(
            selected=_EMPTY_NP_ARRAY_BOOL,
            n_selected=np.int32(0),
            selected_indices=_EMPTY_NP_ARRAY_INT32,
            con_values=_EMPTY_NP_ARRAY_INT32,
            score=_PLACEHOLDER_SCORE,
        )


# singletons to avoid repeated, unnecessary allocations
# (a cleared snapshot's fields are never read — SolverState._depth delimits the live stack entries)
_EMPTY_NP_ARRAY_BOOL = np.array([], dtype=np.bool)
_EMPTY_NP_ARRAY_INT32 = np.array([], dtype=np.int32)
_PLACEHOLDER_SCORE = Score(size=0.0, constraints=0.0, diversity=0.0, div_tie_breakers=())
