from __future__ import annotations

from functools import cached_property

import numpy as np
from numpy.typing import NDArray
from sortedcontainers import SortedSet

from max_div.sampling._constraint_helpers import _build_array_repr, _build_con_membership, _np_con_total_violation

from ._constraints import Constraint
from ._distance import (
    DistanceMetric,
    compute_pdist,
    compute_separation,
    update_separation_add,
    update_separation_remove,
)
from ._diversity import DiversityMetric, compute_diversity


class SolverState:
    """Abstract base class for solver state management."""

    # -------------------------------------------------------------------------
    #  Construction & Configuration
    # -------------------------------------------------------------------------
    def __init__(
        self,
        m: np.int32,
        target_selection_size: np.int32,
        d: NDArray[np.float32],
        diversity_metric: DiversityMetric,
        selected: SortedSet,
        not_selected: SortedSet,
        sep_global: NDArray[np.float32],
        sep_selected: NDArray[np.float32],
        con_values: NDArray[np.int32],
        con_indices: NDArray[np.int32],
        con_membership: dict[np.int32, list[np.int32]],
    ):
        """
        Initialize the SolverState.  The constructor is not intended to be used directly, instead use either new()
        or copy().

        :param m: (np.int32) number of vectors
        :param target_selection_size: (np.int32) target number of selected vectors
        :param d: (np.ndarray[np.float32]) condensed pair-wise distance vector (1D array of size (m*(m-1))//2)
        :param diversity_metric: (DiversityMetric) The diversity metric to use.
        :param selected: (SortedSet) set of selected indices (np.int32)
        :param not_selected: (SortedSet) set of not selected indices (np.int32)
        :param sep_global: (np.ndarray[np.float32]) m x 1 array with separation of each vector wrt the others
        :param sep_selected: (np.ndarray[np.float32]) m x 1 array with separation of each vector wrt selected set
        :param con_values: (np.ndarray[np.int32] | None) upper/lower bounds per constraint (m x 2 array of float32)
                                                                     (as generated by _build_array_repr)
        :param con_indices: (np.ndarray[np.int32] | None) 1d array with all indices per constraint
                                                                     (as generated by _build_array_repr)
        :param con_membership: (dict[np.int32, list[np.int32]] | None) mapping from index to list of constraints it belongs to
                                                                     (as generated by _build_con_membership)
        """
        self._m = m  # READ-ONLY
        self._target_selection_size = target_selection_size  # READ-ONLY

        # distances
        self._d = d  # READ-ONLY
        self._sep_global = sep_global  # READ-ONLY
        self._sep_selected = sep_selected

        # diversity
        self._diversity_metric = diversity_metric  # READ-ONLY

        # selection
        self._selected = selected
        self._not_selected = not_selected

        # constraints
        self._con_values = con_values  # min/max counts of extra samples needed on top of current selection
        self._con_indices = con_indices  # READ-ONLY
        self._con_membership = con_membership  # READ-ONLY

    pass

    # -------------------------------------------------------------------------
    #  API - Modification
    # -------------------------------------------------------------------------
    def copy(self) -> SolverState:
        """Copy the solver-state in a way that modifications to the copy do not affect the original."""
        return SolverState(
            m=self._m,  # READ-ONLY, no copy required
            d=self._d,  # READ-ONLY, no copy required
            diversity_metric=self._diversity_metric,  # READ-ONLY, no copy required
            selected=self._selected.copy(),
            not_selected=self._not_selected.copy(),
            sep_global=self._sep_global,  # READ-ONLY, no copy required
            sep_selected=self._sep_selected.copy(),
            con_values=self._con_values.copy(),
            con_indices=self._con_indices,  # READ-ONLY, no copy required
            con_membership=self._con_membership,  # READ-ONLY, no copy required,
        )

    def add(self, index: int | np.int32):
        # --- validation ----------------------------------
        index = np.int32(index)
        if index in self._selected:
            raise ValueError("Cannot add index that is already selected.")

        # --- selection -----------------------------------
        self._selected.add(index)
        self._not_selected.remove(index)

        # --- separation ----------------------------------
        update_separation_add(self._sep_selected, self._d, self._m, index)

        # --- constraints ---------------------------------
        for i_con in self._con_membership[index]:
            self._con_values[i_con, 0] -= 1  # decrease min_count
            self._con_values[i_con, 1] -= 1  # decrease max_count

    def remove(self, index: int | np.int32):
        # --- validation ----------------------------------
        index = np.int32(index)
        if index in self._not_selected:
            raise ValueError("Cannot remove index that is not selected.")

        # --- selection -----------------------------------
        self._selected.remove(index)
        self._not_selected.add(index)

        # --- separation ----------------------------------
        update_separation_remove(self._sep_selected, self._d, self._m, index, self.selected_index_array)

        # --- constraints ---------------------------------
        for i_con in self._con_membership[index]:
            self._con_values[i_con, 0] += 1  # increase min_count
            self._con_values[i_con, 1] += 1  # increase max_count

    # -------------------------------------------------------------------------
    #  Properties
    # -------------------------------------------------------------------------
    @cached_property
    def has_constraints(self) -> bool:
        """Return True if constraints are defined."""
        return self._con_values.shape[0] > 0

    @property
    def selected_index_array(self) -> NDArray[np.int32]:
        """Return selected indices as a numpy array of np.int32."""
        return np.array(self._selected, dtype=np.int32)

    @property
    def not_selected_index_array(self) -> NDArray[np.int32]:
        """Return not selected indices as a numpy array of np.int32."""
        return np.array(self._not_selected, dtype=np.int32)

    @property
    def selected_separation_array(self) -> NDArray[np.float32]:
        """Return separation of selected vectors wrt other selected vectors as a numpy array of np.float32."""
        return self._sep_selected[list(self._selected)]

    @property
    def not_selected_separation_array(self) -> NDArray[np.float32]:
        """Return separation of not selected vectors wrt selected vectors as a numpy array of np.float32."""
        return self._sep_selected[list(self._not_selected)]

    # -------------------------------------------------------------------------
    #  Diversity
    # -------------------------------------------------------------------------
    @property
    def sample_count_mismatch(self) -> np.int32:
        """Return difference between number of selected samples and required number of samples."""
        return np.int32(abs(len(self._selected) - self._target_selection_size))

    @property
    def constraint_violation(self) -> np.int32:
        """Return total constraint violation (sum of all min_count violations)."""
        if not self.has_constraints:
            return np.int32(0)
        else:
            return _np_con_total_violation(self._con_values)

    @property
    def diversity(self) -> np.float32:
        return compute_diversity(self.selected_separation_array, self._diversity_metric)

    @property
    def score(self) -> tuple[np.int32, np.int32, np.float32]:
        """
        Return overall score of the current selection as (-sample_count_mismatch, -constraint_violation, diversity).
        The first 2 elements are <=0, while the last element is >=0.  The tuple is constructed such that higher is better
        and tuple-comparison prioritizes sample count match first, then constraint satisfaction, and finally diversity.
        """
        return (
            -self.sample_count_mismatch,
            -self.constraint_violation,
            self.diversity,
        )

    # -------------------------------------------------------------------------
    #  Factory methods
    # -------------------------------------------------------------------------
    @classmethod
    def new(
        cls,
        vectors: np.ndarray,
        target_selection_size: int,
        distance_metric: DistanceMetric,
        diversity_metric: DiversityMetric,
        constraints: list[Constraint],
    ) -> SolverState:
        # --- distances ---
        m = np.int32(vectors.shape[0])
        d = compute_pdist(vectors, distance_metric)
        sep_global = compute_separation(d, m)
        sep_selected = np.full(m, fill_value=np.inf, dtype=np.float32)

        # --- selection ---
        selected = SortedSet()
        not_selected = SortedSet(np.arange(m, dtype=np.int32))

        # --- constraints ---
        con_values, con_indices = _build_array_repr(constraints)
        con_membership = _build_con_membership(m, constraints)

        # --- construct & return ---
        return SolverState(
            m,
            np.int32(target_selection_size),
            d,
            diversity_metric,
            selected,
            not_selected,
            sep_global,
            sep_selected,
            con_values,
            con_indices,
            con_membership,
        )
